### PR TITLE
Backport of JDK-8210875: Refactor CompactHashtable

### PR DESCRIPTION
**Pull request by y1yang0**
Hi all,

Please help review this backport.

Original issue: https://bugs.openjdk.java.net/browse/JDK-8210875
Github webrev: https://github.com/kelthuzadx/jdk/commit/6c59cb232fc7d140a5f7fa24aef02f885dd007b7

This backport can not apply cleanly. Many problems should be addressed. Most of them are caused by the lack of backporting of [JDK-8195100 Use a low latency hashtable for SymbolTable](https://bugs.openjdk.java.net/browse/JDK-8195100), we can fix these problems by simply refactoring(see below) the code without any semantic changes, that's actually what this patch did. Another way to address these problems is trying to backport JDK-8195100. If you think it's necessary to backport JDK-8195100, I'd like to do so.

1. In vmStructs.cpp
We should remove SymbolHashtable/SymbolHashtableEntry, SymbolCompactHashTable and RehashableSymbolHashtable because they no longer exist after this backport.

2. In javaClasses.cpp
Original changes:
```
-  oop classname = StringTable::intern((char*) str, CHECK);
+  oop classname = StringTable::intern(str, CHECK);
```
But the current source code uses java_lang_Class::name to get the name instead of StringTable::intern, so it remains unchanged for now.
```
oop classname = java_lang_Class::name(java_class, CHECK);
```

3. In symbolTable.cpp
- Remove SymbolTable::encode_shared/decode_shared since they are not referenced and fail to compile.
-  Notably in SymbolTable::write_to_archive, I create `copy_shared_symbol_table` and iterate symbol table within it.

There are some minor adjustments other than listed above, please see the patch diff for details :)

Testing:
- hotspot:tier1
- hotspot/jtreg/appcds(slowdebug)

Thanks,
Yang

### CODE REVIEW

**Comment by y1yang0** [comment]
When running tests under runtime/appcds, DirClasspathTest.java was failed due to the following reason:
```
java.nio.file.FileAlreadyExistsException: /home/qingfeng.yy/jdk11u-fast-startup-incubator/JTwork/classes/0/runtime/appcds/DirClasspathTest.d/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Hello.class
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:573)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
	at java.base/java.nio.file.Files.copy(Files.java:1295)
	at DirClasspathTest.main(DirClasspathTest.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
I have proved this problem is not caused by backport pathces. There are same errors on https://bugs.openjdk.java.net/browse/JDK-8231097 , and this issue status is "Resolved". After a simple attempt to the solution proposed by ccheung, the test still fails.

**Review by jianglizhou — CHANGES_REQUESTED** [review]
I have a version of internal backport for JDK-8210875, which addresses dependencies caused by JDK-8195100 and avoids pulling in JDK-8195100. JDK-8195100 has many dependencies and is not directly related to CDS.

I can create a PR for JDK-8210875 backport, if you are okay with closing yours.

**Comment by y1yang0** [comment]
> ulling in

Thank you jiangli, please feel free to do so.

**Comment by jianglizhou** [comment]
I created https://github.com/adoptium/jdk11u-fast-startup-incubator/pull/15 for JDK-8210875 backport. Please review.

**Comment by jianglizhou** [comment]
https://github.com/adoptium/jdk11u-fast-startup-incubator/pull/15 would merge all your existing commits in dev into master. Not sure if that should be done. I closed the pull request. Please let me know your current steps of working with the 'dev' branch for new pull request.

On a related note, what's our plan for merging changes from 'dev' to 'master'?

**Comment by y1yang0** [comment]
> #15 would merge all your existing commits in dev into master. Not sure if that should be done. I closed the pull request. Please let me know your current steps of working with the 'dev' branch for new pull request.

I think we can firstly merge https://github.com/adoptium/jdk11u-fast-startup-incubator/pull/13 into dev and then merge dev into master.

> 
> On a related note, what's our plan for merging changes from 'dev' to 'master'?

I plan to backport all preliminary patches into dev and merge them into master.  But it's okay, you can merge them into master even if they are not all ready. IMO, `dev` means `temporary`. I propose to follow master-based development later, i.e. all later PRs should target to master branch.

**Comment by jianglizhou** [comment]
Thanks Yi Yang. Merged your existing committed backports to 'master' with PR #15. I created a new pull request https://github.com/adoptium/jdk11u-fast-startup-incubator/pull/17 for JDK-8210875 backport, because the backport was reverted in PR #15. Please take another look. Apologize for these noises.

**Comment by jianglizhou** [comment]
Yi Yang, this PR can be closed now. Thanks.

**Comment by y1yang0** [comment]
Absolutely, since 8210875 is merged into master. I would backport the remaining patches in order later.
```
DONE 	JDK-8213713: Minor issues during MetaspaceShared::initialize_runtime_shared_and_meta_spaces.
DONE	JDK-8210875: Refactor CompactHashtable
		JDK-8210388: Use hash table to store archived subgraph_info records.
DONE 	JDK-8209971: TestOptionsWithRanges.java crashes in CDS mode with G1UpdateBufferSize=1.
DONE 	JDK-8210864: Reduce the use of metaspaceShared.hpp
		JDK-8206009: Move CDS java heap object archiving code to heapShared.hpp and heapShared.cpp.
DONE	JDK-8213587: Speed up CDS dump time by using resizable hashtables.
DONE	JDK-8214756: SA should ignore archived java heap objects that are not in use.
DONE	JDK-8218751: Do not store original classfiles inside the CDS archive.
DONE	JDK-8221621: FindTests.gmk cannot handle "=" in TEST.groups comments.
		JDK-8221351: Crash in KlassFactory::check_shared_class_file_load_hook.
DONE	JDK-8213898: CDS dumping of springboot asserts in G1ArchiveAllocator::alloc_new_region.
		JDK-8214388: CDS dumping fails with java heap fragmentation.
DONE	JDK-8213563: appcds/sharedStrings/SharedStringsStress.java fails with 'GC triggered before VM initialization completed' error.
DONE	JDK-8231895: Avoid String allocations in JVM_FindLoadedClass.
```

**Pull request closed without merging**
