### PR TITLE
Backport of JDK-8213587: Speed up CDS dump time by using resizable hashtables

### PR DESCRIPTION
**Pull request by y1yang0**
Hi all,

Please help review this trivial backport.

Original issue: https://bugs.openjdk.java.net/browse/JDK-8213587
HG webrev: http://hg.openjdk.java.net/jdk/jdk/rev/3009ca99de32
Review efforts: Medium

This backport applies relatively cleanly.

One nit: it can not compile after applying this backport due to incomplete type in classLoaderExt.cpp. After reverting the removal of `#include "classfile/classListParser.hpp"`, it compiles without any complains.

Thanks,
Yang

### CODE REVIEW

**Comment by y1yang0** [comment]
It seems that the remaining patches should be backported in order, so I'll leave them until JDK-8210875 is finished.
````
DONE 	JDK-8213713: Minor issues during MetaspaceShared::initialize_runtime_shared_and_meta_spaces.
		JDK-8210875: Refactor CompactHashtable
		JDK-8210388: Use hash table to store archived subgraph_info records.
DONE 	JDK-8209971: TestOptionsWithRanges.java crashes in CDS mode with G1UpdateBufferSize=1.
DONE 	JDK-8210864: Reduce the use of metaspaceShared.hpp
		JDK-8206009: Move CDS java heap object archiving code to heapShared.hpp and heapShared.cpp.
XXXX	JDK-8213587: Speed up CDS dump time by using resizable hashtables.
XXXX	JDK-8214756: SA should ignore archived java heap objects that are not in use.
XXXX	JDK-8218751: Do not store original classfiles inside the CDS archive.
XXXX	JDK-8221621: FindTests.gmk cannot handle "=" in TEST.groups comments.
		JDK-8221351: Crash in KlassFactory::check_shared_class_file_load_hook.
XXXX	JDK-8213898: CDS dumping of springboot asserts in G1ArchiveAllocator::alloc_new_region.
		JDK-8214388: CDS dumping fails with java heap fragmentation.
XXXX	JDK-8213563: appcds/sharedStrings/SharedStringsStress.java fails with 'GC triggered before VM initialization completed' error.
XXXX	JDK-8231895: Avoid String allocations in JVM_FindLoadedClass.
```

**Comment by jianglizhou** [comment]
LGTM. 

For comparison, following are my notes from internal JDK-8213587 backport that I did more than a year ago:

> Manually applied diff in src/hotspot/share/memory/metaspaceShared.cpp and test/hotspot/jtreg/runtime/appcds/TestCommon.java without modification.
> 
> Reverted the #include "classfile/classListParser.hpp" in classLoaderExt.cpp. The #include is needed by ClassLoaderExt::load_one_class. ClassLoaderExt::load_one_class was removed by JDK-8213346, which is not applied in JDK 11 yet (pulls in more dependencies).

**Review by jianglizhou — APPROVED** [review]
LGTM

**Comment by jianglizhou** [comment]
> It seems that the remaining patches should be backported in order, so I'll leave them until JDK-8210875 is finished.
> 
> ```
> DONE 	JDK-8213713: Minor issues during MetaspaceShared::initialize_runtime_shared_and_meta_spaces.
> 		JDK-8210875: Refactor CompactHashtable
> 		JDK-8210388: Use hash table to store archived subgraph_info records.
> DONE 	JDK-8209971: TestOptionsWithRanges.java crashes in CDS mode with G1UpdateBufferSize=1.
> DONE 	JDK-8210864: Reduce the use of metaspaceShared.hpp
> 		JDK-8206009: Move CDS java heap object archiving code to heapShared.hpp and heapShared.cpp.
> XXXX	JDK-8213587: Speed up CDS dump time by using resizable hashtables.
> XXXX	JDK-8214756: SA should ignore archived java heap objects that are not in use.
> XXXX	JDK-8218751: Do not store original classfiles inside the CDS archive.
> XXXX	JDK-8221621: FindTests.gmk cannot handle "=" in TEST.groups comments.
> 		JDK-8221351: Crash in KlassFactory::check_shared_class_file_load_hook.
> XXXX	JDK-8213898: CDS dumping of springboot asserts in G1ArchiveAllocator::alloc_new_region.
> 		JDK-8214388: CDS dumping fails with java heap fragmentation.
> XXXX	JDK-8213563: appcds/sharedStrings/SharedStringsStress.java fails with 'GC triggered before VM initialization completed' error.
> XXXX	JDK-8231895: Avoid String allocations in JVM_FindLoadedClass.
> ```
> ```

Yi Yang, I just checked my internal backport records. Most of the remaining ones can be backported cleanly. The following two required some changes on top of the backport. I will do these (in the order) after you backport the dependencies for each. We can coordinate together. 

JDK-8221351
JDK-8214388

**Comment by y1yang0** [comment]
Thanks for checking. Just so I don't screw this up, do you mean I should backport JDK-8210875, JDK-8210388, JDK-8206009? then you would backport JDK-8221351 and JDK-8214388? If so, I will prepare these backport patches as soon as possible.

**Comment by jianglizhou** [comment]
Yes. Thanks! I'll start the process for JDK-8221351 once you are done with JDK-8214756.

**Pull request merged**
